### ISSUE TITLE
Is this compatible with Laravel 5.0?

### ISSUE THREAD

**Issue by lukeberry99** [Snowfire/Laravel-Postmark-Driver#4]
Is this compatible with L5? Currently getting this error when installing:

`[ErrorException]                                                                                                                                                    
  Declaration of Snowfire\Mail\MailServiceProvider::registerSwiftTransport() should be compatible with Illuminate\Mail\MailServiceProvider::registerSwiftTransport()`

Works fine on Laravel 4, currently migrating our app over to Laravel 5.

**Comment by emilsundberg** [comment]
I'm sorry. This package only works in Laravel 4.* since they have made changes to how mail works in L5.

**Comment by lukeberry99** [comment]
Are there any plans for this package to be upgraded for Laravel 5?

**Comment by emilsundberg** [comment]
I haven't investigated how mail adapters works in L5. I think Postmark should be included as a default driver. I will have a look once I start migrating over my L4 projects that require Postmark.

You could try to change the code to make it work and send me a PR. Or the simple way, use Mandrill instead of Postmark for now.

**Comment by lukeberry99** [comment]
Postmark is pretty integral to our apps, I'll take a look into mail adapters and try and get it working.

Thanks :)
